In [2]:
import numpy as np
import pandas as pd
from sklearn import tree
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', 500)

In [3]:
df = pd.read_csv('data/liwc_categorical_scores_full.csv') 
X = df[ ['achieve','adj', 'adverb', 'affect', 'affiliation', 'anger', 'anx', 'article', 'assent', 'auxverb', 'bio', 'body', 'cause','certain', 'cogproc', 'compare', 'conj', 'death', 'differ', 'discrep', 'drives', 'family','feel', 'female', 'filler', 'focusfuture', 'focuspast', 'focuspresent','friend', 'function', 'health', 'hear', 'home', 'i', 'informal', 'ingest', 'insight', 'interrog', 'ipron','leisure', 'male', 'money', 'motion', 'negate', 'negemo', 'netspeak', 'nonflu', 'number', 'percept', 'posemo', 'power','ppron', 'prep', 'pronoun', 'quant', 'relativ', 'relig','reward', 'risk', 'sad', 'see','sexual', 'shehe', 'social', 'space', 'swear', 'tentat', 'they', 'time', 'verb', 'we','work', 'you']]
feature_names = X.columns
y = df['party']
feature_list = list(X)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [5]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100,  
max_features = 'sqrt',  
n_jobs=-1, verbose = 1)

# Fit on training data

model.fit(X_train, y_train)  

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    0.2s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    0.7s finished


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=None, verbose=1,
            warm_start=False)

In [6]:
rf_predictions = model.predict(X_test) 
rf_probs = model.predict_proba(X_test)[:, 1]

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.1s finished


In [7]:

pred_bi_y = []
for i in rf_predictions:
    if i == 'republicans':
        v =1
        pred_bi_y.append(v)
    if i == 'democrats':
        v =0
        pred_bi_y.append(v)
    else:
        pass
    
len(pred_bi_y)

880

In [8]:
real_bi_y = []
for i in y_test:
    if i == 'republicans':
        v =1
        real_bi_y.append(v)
    if i == 'democrats':
        v =0
        real_bi_y.append(v)
    else:
        pass
    
len(real_bi_y)

880

In [9]:
from sklearn.metrics import roc_auc_score
roc_value = roc_auc_score(real_bi_y, rf_probs)
roc_value

0.9057784120394395

In [10]:
from sklearn.metrics import f1_score
f1_value = f1_score(real_bi_y, pred_bi_y)
f1_value

0.8138728323699422

In [35]:
from sklearn.metrics import precision_score
precision_score = precision_score(real_bi_y, pred_bi_y)
precision_score

0.7736263736263737

In [42]:
from  sklearn.metrics import classification_report
>>> target_names = [ 'republicans','democrats']
>>> print(classification_report(real_bi_y, pred_bi_y, target_names=target_names))

              precision    recall  f1-score   support

 republicans       0.86      0.78      0.82       470
   democrats       0.77      0.86      0.81       410

   micro avg       0.82      0.82      0.82       880
   macro avg       0.82      0.82      0.82       880
weighted avg       0.82      0.82      0.82       880



In [12]:
#from keras.models #import load_model
from treeinterpreter import treeinterpreter as ti
# fit a scikit-learn's regressor model

# rf = RandomForestRegressor()

# rf.fit(trainX, trainY)

prediction, bias, contributions = ti.predict(model, X_test)


In [13]:
prediction[0]

array([0.21, 0.79])

In [14]:
bias[0]

array([0.48935227, 0.51064773])

In [15]:
contributions[0]

array([[-0.00230395,  0.00230395],
       [-0.00372617,  0.00372617],
       [-0.00627668,  0.00627668],
       [ 0.00521535, -0.00521535],
       [ 0.04626087, -0.04626087],
       [-0.00361773,  0.00361773],
       [-0.0199644 ,  0.0199644 ],
       [-0.0075175 ,  0.0075175 ],
       [ 0.00221837, -0.00221837],
       [-0.0073131 ,  0.0073131 ],
       [-0.00525483,  0.00525483],
       [-0.00619522,  0.00619522],
       [ 0.00044824, -0.00044824],
       [-0.03773163,  0.03773163],
       [-0.04236452,  0.04236452],
       [-0.01450481,  0.01450481],
       [ 0.01184107, -0.01184107],
       [ 0.0009458 , -0.0009458 ],
       [-0.04952243,  0.04952243],
       [-0.0568896 ,  0.0568896 ],
       [-0.00502737,  0.00502737],
       [-0.00265983,  0.00265983],
       [ 0.01227757, -0.01227757],
       [-0.01691689,  0.01691689],
       [ 0.        ,  0.        ],
       [-0.00312527,  0.00312527],
       [-0.00413803,  0.00413803],
       [-0.00906244,  0.00906244],
       [-0.00283871,

In [16]:
sorted(zip(model.feature_importances_, feature_names), reverse=True)

[(0.05718203241990027, 'discrep'),
 (0.0551682692912299, 'differ'),
 (0.04954544467955745, 'negate'),
 (0.04886799821519201, 'cogproc'),
 (0.04457961200337582, 'negemo'),
 (0.03476452767647215, 'anger'),
 (0.028180834096643455, 'relig'),
 (0.026588168408912836, 'female'),
 (0.023397483672626517, 'posemo'),
 (0.021778846289986817, 'certain'),
 (0.020104268336264237, 'anx'),
 (0.01765096618971216, 'bio'),
 (0.01715432804730215, 'risk'),
 (0.014953380671054242, 'auxverb'),
 (0.014788118328667136, 'verb'),
 (0.014527293470443438, 'health'),
 (0.013465075123068264, 'space'),
 (0.013181088703341608, 'reward'),
 (0.013096210790782652, 'hear'),
 (0.012681107191084985, 'work'),
 (0.012546487372289437, 'leisure'),
 (0.012434756217489313, 'article'),
 (0.01183700890306837, 'social'),
 (0.011108372914262421, 'relativ'),
 (0.011039979123830552, 'motion'),
 (0.011038033505491797, 'family'),
 (0.011009455225521231, 'focuspresent'),
 (0.010840779466479435, 'affect'),
 (0.010716365185731713, 'affiliati

In [34]:
# Import tools needed for visualization
import os
os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin/'
from sklearn.tree import export_graphviz
import pydot
import graphviz
# Pull out one tree from the forest
tree = model.estimators_[5]
# Export the image to a dot file
export_graphviz(tree, out_file = 'tree.dot', feature_names = feature_list, class_names = ( 'republicans','democrats'),filled = True,rounded = True)
# Use dot file to create a graph
(graph, ) = pydot.graph_from_dot_file('tree.dot')
# Write graph to a png file
graph.write_png('tree.png')